apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: instavote
images:
- name: schoolofdevops/vote
  newName: simoganger/vote
  newTag: main-8395e460-1775559122 #{"$imagepolicy": "flux-system:vote:tag"}
replicas:
- name: vote
  count: 4
configMapGenerator:
- name: vote
  literals:
  - OPTION_A=FluxCD
  - OPTION_B=ArgoCD
